# Mock Trading Server Configuration
# Place this file in the same directory as the mock-trading-server binary and rename to configuration.toml

# SSL/TLS Configuration
# Note: With rustls, cipher_list is ignored (rustls uses secure defaults)
private_key="localhost.key"
cert_chain="localhost.crt"
use_ssl=false
cipher_list="ECDHE-RSA-AES128-GCM-SHA256,ECDHE-RSA-AES256-GCM-SHA384"

# Server Configuration
port=8888
host="0.0.0.0"
