---
# ultra_low_latency_trading_remediation.yml
- name: Fix Ultra-Low Latency Trading System Configuration Issues
  hosts: aws_ec2
  become: yes
  gather_facts: no
  
  tasks:
    - name: Fix kernel workqueue affinity
      ansible.builtin.shell: |
        find /sys/devices/virtual/workqueue -name cpumask -exec sh -c 'echo 3 > {}' \;
      changed_when: true

    - name: Fix writeback NUMA affinity
      ansible.builtin.shell: |
        echo 0 > /sys/bus/workqueue/devices/writeback/numa
      changed_when: true
      ignore_errors: yes

    - name: Fix Transparent Huge Pages settings
      ansible.builtin.shell: |
        echo never > /sys/kernel/mm/transparent_hugepage/enabled
        echo never > /sys/kernel/mm/transparent_hugepage/defrag
        # Ensure persistence across reboots
        sed -i 's/transparent_hugepage=.*/transparent_hugepage=never/' /etc/default/grub
      changed_when: true
      ignore_errors: yes

    - name: Update GRUB configuration
      ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
      ignore_errors: yes

    - name: Fix memory sysctl parameters
      ansible.builtin.shell: |
        sysctl -w vm.swappiness=0
        sysctl -w vm.zone_reclaim_mode=0
        sysctl -w vm.max_map_count=262144
        sysctl -w vm.min_free_kbytes=1000000
        sysctl -w vm.dirty_ratio=80
        sysctl -w vm.dirty_background_ratio=5
        sysctl -w vm.vfs_cache_pressure=50
        sysctl -w vm.mlockall=1
        sysctl -w vm.compaction_proactiveness=0
        sysctl -w vm.compact_unevictable_allowed=0
        sysctl -w vm.dirty_background_bytes=33554432
        sysctl -w vm.dirty_bytes=268435456
        sysctl -w vm.dirty_expire_centisecs=3000
        sysctl -w vm.dirty_writeback_centisecs=10
        sysctl -p /etc/sysctl.d/99-trading-memory.conf
      changed_when: true
      ignore_errors: yes

    - name: Fix network interface offload settings - enp39s0
      ansible.builtin.shell: |
        ethtool -K enp39s0 rx off tx off sg off gso off gro off tso off ufo off lro off
        ethtool -C enp39s0 adaptive-rx off rx-usecs 1 tx-usecs 1
      changed_when: true
      ignore_errors: yes

    - name: Fix I/O scheduler settings
      ansible.builtin.shell: |
        for DISK in $(lsblk -d -o NAME | grep -v NAME); do
          if [ -f "/sys/block/$DISK/queue/scheduler" ]; then
            echo "mq-deadline" > /sys/block/$DISK/queue/scheduler 2>/dev/null || echo "none" > /sys/block/$DISK/queue/scheduler
          fi
        done
      changed_when: true
      ignore_errors: yes

    - name: Stop and disable amazon-ssm-agent service
      ansible.builtin.systemd:
        name: amazon-ssm-agent
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Run validation playbook again to verify fixes
      ansible.builtin.debug:
        msg: "All remediation steps completed. Please run the validation playbook again to verify all issues have been resolved."

    - name: Reboot system to apply all changes
      ansible.builtin.reboot:
        reboot_timeout: 600
        post_reboot_delay: 30
        msg: "Rebooting to apply ultra-low latency tuning fixes"
        connect_timeout: 60
        test_command: uptime
