name: Build Pull Request

on: [pull_request]

permissions:
  contents: read

jobs:
  java-client:
    name: Build Java Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn clean package -DskipTests
      
      - name: Run tests
        run: mvn test
      
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-client-jar
          path: target/*.jar
          retention-days: 7

  rust-server:
    name: Build Rust Mock Trading Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mock-trading-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      
      - name: Check formatting
        run: cargo fmt --check
        continue-on-error: true
      
      - name: Run Clippy
        run: cargo clippy -- -D warnings
        continue-on-error: true
      
      - name: Build
        run: cargo build --release
      
      - name: Run tests
        run: cargo test
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: rust-server-binary
          path: mock-trading-server/target/release/mock-trading-server
          retention-days: 7

  cpp-client:
    name: Build C++ Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cpp-client
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libssl-dev libboost-all-dev
      
      - name: Create build directory
        run: mkdir -p build
      
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
      - name: Build
        run: cmake --build build --config Release
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: cpp-client-binary
          path: cpp-client/build/*
          retention-days: 7

  cdk-infrastructure:
    name: Build CDK Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: deployment/cdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: deployment/cdk/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build TypeScript
        run: npm run build
      
      - name: Run tests
        run: npm test
        continue-on-error: true
      
      - name: Synthesize CDK
        run: npx cdk synth
      
      - name: Upload CDK template
        uses: actions/upload-artifact@v4
        with:
          name: cdk-template
          path: deployment/cdk/cdk.out
          retention-days: 7

  af-xdp-benchmark:
    name: Build AF_XDP Benchmark
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: af_xdp_zero_copy_perf_benchmark
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libbpf-dev libxdp-dev
        continue-on-error: true
      
      - name: Build AF_XDP components
        run: make
        continue-on-error: true
